name: A880-JAVACORE-CI

# Controls when the workflow will run V2
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: bake-ci
    runs-on: self-hosted
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: Install OpenJDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8'
 
      - name: Set up Maven
        run: |
          curl -Lo maven.tar.gz https://archive.apache.org/dist/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.tar.gz
          tar xzf maven.tar.gz
          echo "$(pwd)/apache-maven-3.8.2/bin" >> $GITHUB_PATH

      - name: QCP Pipeline CI
        uses: qantas-cloud/c031-pipeline/actions/ci-action@master
        
